#!/usr/bin/env bash
# asdf compatibility layer.
#
# Plenty of asdf plugins shell out to `asdf` from inside their own hooks:
# asdf-nodejs ends bin/install with `asdf reshim nodejs $version`, and other
# plugins call `asdf where` or `asdf list`. Those plugins only work if an
# `asdf` executable is on PATH while the hook runs.
#
# polyvm generates a small translating `asdf` and puts its directory on PATH
# for hook execution only, never for the user's own shell.

POLYVM_ASDF_COMPAT_VERSION="v0.14.1"

polyvm_ensure_asdf_compat() {
  local shim="${POLYVM_COMPAT_DIR}/asdf"
  local polyvm_bin="${POLYVM_DIR}/bin/polyvm"

  # Regenerate when missing or older than the CLI it wraps.
  if [ -x "$shim" ] && [ ! "$polyvm_bin" -nt "$shim" ]; then
    return 0
  fi

  mkdir -p "$POLYVM_COMPAT_DIR"
  cat > "$shim" <<COMPAT
#!/usr/bin/env bash
# Generated by polyvm. Translates asdf calls made from inside plugin hooks.
# Do not edit; it is rewritten whenever polyvm changes.
set -uo pipefail
POLYVM_BIN="${polyvm_bin}"
COMPAT
  cat >> "$shim" <<'COMPAT'

cmd="${1:-}"
[ $# -gt 0 ] && shift

case "$cmd" in
  reshim)      exec "$POLYVM_BIN" reshim "$@" ;;
  where)       exec "$POLYVM_BIN" where "$@" ;;
  which)       exec "$POLYVM_BIN" which "$@" ;;
  current)     exec "$POLYVM_BIN" current "$@" ;;
  install)     exec "$POLYVM_BIN" install "$@" ;;
  uninstall)   exec "$POLYVM_BIN" uninstall "$@" ;;
  exec)        exec "$POLYVM_BIN" exec "$@" ;;
  env)         exec "$POLYVM_BIN" env "$@" ;;
  latest)      exec "$POLYVM_BIN" latest "$@" ;;
  global)      exec "$POLYVM_BIN" global "$@" ;;
  local)       exec "$POLYVM_BIN" local "$@" ;;
  shell)       exec "$POLYVM_BIN" shell-env "$@" ;;
  plugin-add)    exec "$POLYVM_BIN" plugin add "$@" ;;
  plugin-list)   exec "$POLYVM_BIN" plugin list "$@" ;;
  plugin-remove) exec "$POLYVM_BIN" plugin remove "$@" ;;
  plugin-update) exec "$POLYVM_BIN" plugin update "$@" ;;
  plugin|plugins) exec "$POLYVM_BIN" plugin "$@" ;;
  list)
    if [ "${1:-}" = "all" ]; then
      shift
      exec "$POLYVM_BIN" list-all "$@"
    fi
    # Plugins word-split this output, so print bare version names with no
    # indentation and no current-version marker.
    "$POLYVM_BIN" list "$@" | sed -e 's/^[[:space:]]*//' -e 's/^\*//'
    ;;
  version|--version|-v)
    printf '%s\n' "$POLYVM_ASDF_COMPAT_VERSION_STRING"
    ;;
  "")
    exec "$POLYVM_BIN" help
    ;;
  *)
    exec "$POLYVM_BIN" "$cmd" "$@"
    ;;
esac
COMPAT
  # Bake the reported asdf version in.
  sed -i.bak "s|\$POLYVM_ASDF_COMPAT_VERSION_STRING|${POLYVM_ASDF_COMPAT_VERSION}|" "$shim" 2>/dev/null \
    || sed -i "" "s|\$POLYVM_ASDF_COMPAT_VERSION_STRING|${POLYVM_ASDF_COMPAT_VERSION}|" "$shim"
  rm -f "${shim}.bak"
  chmod +x "$shim"
}
