#!/usr/bin/env bash
# polyvm shims.
#
# Every executable a plugin installs gets a stub in $POLYVM_SHIM_DIR, which
# sits on PATH. Running `node` runs the stub, which asks polyvm which version
# applies to the current directory and execs the real binary. That is why
# polyvm works inside scripts, cron jobs and editors with no shell
# integration at all.
#
# Each stub carries provenance lines so the dispatcher knows which plugins and
# versions ship that command:
#
#   # polyvm-plugin: nodejs 22.3.0

# polyvm_bin_paths <plugin> <version_dirname>  -> absolute dirs, one per line
polyvm_bin_paths() {
  local plugin="$1" dirname="$2"
  local install_path="${POLYVM_INSTALL_DIR}/${plugin}/${dirname}"
  local raw="bin"

  if polyvm_plugin_has_hook "$plugin" list-bin-paths; then
    ASDF_INSTALL_TYPE="version"
    ASDF_INSTALL_VERSION="$dirname"
    ASDF_INSTALL_PATH="$install_path"
    export ASDF_INSTALL_TYPE ASDF_INSTALL_VERSION ASDF_INSTALL_PATH
    local hook_out
    hook_out="$(polyvm_run_hook "$plugin" list-bin-paths 2>/dev/null || true)"
    [ -n "$hook_out" ] && raw="$hook_out"
  fi

  local p
  for p in $raw; do
    printf '%s\n' "${install_path}/${p}"
  done
}

# polyvm_write_shim <command> <plugin> <version_dirname>
polyvm_write_shim() {
  local cmd="$1" plugin="$2" dirname="$3"
  local shim="${POLYVM_SHIM_DIR}/${cmd}"
  local line="# polyvm-plugin: ${plugin} ${dirname}"

  if [ -f "$shim" ]; then
    # Already claimed by this plugin/version, nothing to do.
    if grep -Fqx "$line" "$shim" 2>/dev/null; then
      return 0
    fi
    # Another plugin or version also ships this command. Append provenance
    # after the existing provenance block.
    local tmp="${shim}.polyvm.$$"
    awk -v newline="$line" '
      BEGIN { inserted = 0; prev = 0 }
      /^# polyvm-plugin:/ { print; prev = 1; next }
      {
        if (prev == 1 && inserted == 0) { print newline; inserted = 1 }
        prev = 0
        print
      }
      END { if (inserted == 0) print newline }
    ' "$shim" > "$tmp"
    mv "$tmp" "$shim"
    chmod +x "$shim"
    return 0
  fi

  mkdir -p "$POLYVM_SHIM_DIR"
  # On Windows a cmd.exe or PowerShell caller cannot run a bash stub, so a
  # .cmd wrapper is written beside it. Harmless everywhere else because it is
  # only generated when running under MSYS, Cygwin or Git Bash.
  if polyvm_is_windows; then
    polyvm_write_shim_cmd "$cmd"
  fi
  cat > "$shim" <<SHIM
#!/usr/bin/env bash
# Generated by polyvm. Do not edit; run \`polyvm reshim\` instead.
${line}
export POLYVM_DIR="\${POLYVM_DIR:-${POLYVM_DIR}}"
export POLYVM_DATA_DIR="\${POLYVM_DATA_DIR:-${POLYVM_DATA_DIR}}"
exec "${POLYVM_DIR}/bin/polyvm" exec-shim "${cmd}" "\$@"
SHIM
  chmod +x "$shim"
}

# Windows entry point: a .cmd that hands off to the bash dispatcher.
polyvm_write_shim_cmd() {
  local cmd="$1"
  local wrapper="${POLYVM_SHIM_DIR}/${cmd}.cmd"
  cat > "$wrapper" <<CMDSHIM
@echo off
REM Generated by polyvm. Do not edit; run \`polyvm reshim\` instead.
bash "${POLYVM_DIR}/bin/polyvm" exec-shim "${cmd}" %*
CMDSHIM
}

# polyvm_reshim <plugin> [version_dirname]
polyvm_reshim() {
  local plugin="$1" dirname="${2:-}"
  polyvm_require_plugin "$plugin"
  mkdir -p "$POLYVM_SHIM_DIR"

  local versions
  if [ -n "$dirname" ]; then
    versions="$dirname"
  else
    versions=""
    local d
    for d in "${POLYVM_INSTALL_DIR}/${plugin}"/*; do
      [ -d "$d" ] || continue
      versions="$versions $(basename "$d")"
    done
  fi

  local v bindir f cmd
  for v in $versions; do
    for bindir in $(polyvm_bin_paths "$plugin" "$v"); do
      [ -d "$bindir" ] || continue
      for f in "$bindir"/*; do
        polyvm_is_executable "$f" || continue
        cmd="$(polyvm_shim_name "$(basename "$f")")"
        # Never shadow polyvm itself.
        [ "$cmd" = "polyvm" ] && continue
        polyvm_write_shim "$cmd" "$plugin" "$v"
      done
    done
    polyvm_run_hook "$plugin" post-install-shim "$v" >/dev/null 2>&1 || true
  done
}

# Rebuild every shim from scratch. Cheap and always correct.
polyvm_reshim_all() {
  mkdir -p "$POLYVM_SHIM_DIR"
  rm -rf "${POLYVM_SHIM_DIR:?}"/*
  polyvm_dir_has_entries "$POLYVM_INSTALL_DIR" || return 0
  local p
  for p in "$POLYVM_INSTALL_DIR"/*; do
    [ -d "$p" ] || continue
    p="$(basename "$p")"
    polyvm_plugin_installed "$p" || continue
    polyvm_reshim "$p"
  done
}

# Plugins that provide a command, newest shim entry first.
polyvm_shim_plugins() {
  local cmd="$1"
  local shim="${POLYVM_SHIM_DIR}/${cmd}"
  [ -f "$shim" ] || return 1
  awk '/^# polyvm-plugin:/ { print $3 }' "$shim" | awk '!seen[$0]++'
}

polyvm_shim_versions_for_plugin() {
  local cmd="$1" plugin="$2"
  local shim="${POLYVM_SHIM_DIR}/${cmd}"
  [ -f "$shim" ] || return 1
  awk -v p="$plugin" '/^# polyvm-plugin:/ && $3 == p { print $4 }' "$shim"
}

# PATH with the shim directory removed, for `system` passthrough.
polyvm_path_without_shims() {
  printf '%s\n' "$PATH" | tr ':' '\n' \
    | grep -v -x -F "$POLYVM_SHIM_DIR" \
    | paste -sd: -
}

# polyvm_resolve_command_var <command>
# Sets POLYVM_CMD_PLUGIN, POLYVM_CMD_VERSION and POLYVM_CMD_PATH.
# Returns 1 when no plugin applies, 2 when a plugin applies but the version it
# asks for is not installed, in which case POLYVM_RESOLVE_HINT names it.
#
# This assigns rather than prints for the same reason the version resolver
# does: a command substitution runs in a subshell, so the hint a caller needs
# for its error message would not survive.
polyvm_resolve_command_var() {
  local cmd="$1"
  local plugins plugin version bindir candidate
  POLYVM_CMD_PLUGIN=""
  POLYVM_CMD_VERSION=""
  POLYVM_CMD_PATH=""
  POLYVM_RESOLVE_HINT=""
  plugins="$(polyvm_shim_plugins "$cmd")" || return 1
  [ -n "$plugins" ] || return 1

  for plugin in $plugins; do
    polyvm_plugin_installed "$plugin" || continue
    version="$(polyvm_resolve_version "$plugin" 2>/dev/null || true)"
    [ -n "$version" ] || continue

    if [ "$version" = "system" ]; then
      POLYVM_CMD_PLUGIN="$plugin"
      POLYVM_CMD_VERSION="system"
      POLYVM_CMD_PATH="system"
      return 0
    fi

    case "$version" in
      path:*)
        candidate="${version#path:}/bin/${cmd}"
        if polyvm_is_executable "$candidate"; then
          POLYVM_CMD_PLUGIN="$plugin"
          POLYVM_CMD_VERSION="$version"
          POLYVM_CMD_PATH="$candidate"
          return 0
        fi
        continue
        ;;
    esac

    local dirname
    dirname="$(polyvm_version_dirname "$version")"
    if [ ! -d "${POLYVM_INSTALL_DIR}/${plugin}/${dirname}" ]; then
      POLYVM_RESOLVE_HINT="${plugin} ${version}"
      continue
    fi

    if polyvm_plugin_has_hook "$plugin" exec-path; then
      local rel
      rel="$(polyvm_run_hook "$plugin" exec-path \
        "${POLYVM_INSTALL_DIR}/${plugin}/${dirname}" "$cmd" "bin/${cmd}" 2>/dev/null || true)"
      if [ -n "$rel" ] && polyvm_is_executable "${POLYVM_INSTALL_DIR}/${plugin}/${dirname}/${rel}"; then
        POLYVM_CMD_PLUGIN="$plugin"
        POLYVM_CMD_VERSION="$dirname"
        POLYVM_CMD_PATH="${POLYVM_INSTALL_DIR}/${plugin}/${dirname}/${rel}"
        return 0
      fi
    fi

    for bindir in $(polyvm_bin_paths "$plugin" "$dirname"); do
      for candidate in "${bindir}/${cmd}" "${bindir}/${cmd}$(polyvm_exe_suffix)"; do
        if polyvm_is_executable "$candidate"; then
          POLYVM_CMD_PLUGIN="$plugin"
          POLYVM_CMD_VERSION="$dirname"
          POLYVM_CMD_PATH="$candidate"
          return 0
        fi
      done
    done
  done

  [ -n "$POLYVM_RESOLVE_HINT" ] && return 2
  return 1
}

# Printing wrapper, kept for callers that only need the path. Loses
# POLYVM_RESOLVE_HINT, so do not use it on an error path.
polyvm_resolve_command() {
  polyvm_resolve_command_var "$1" || return $?
  printf '%s\t%s\t%s\n' "$POLYVM_CMD_PLUGIN" "$POLYVM_CMD_VERSION" "$POLYVM_CMD_PATH"
}

# The entry point every shim calls.
polyvm_exec_shim() {
  local cmd="$1"
  shift
  local rc plugin version target
  polyvm_resolve_command_var "$cmd"
  rc=$?

  if [ $rc -eq 2 ]; then
    polyvm_die "no version of ${POLYVM_RESOLVE_HINT%% *} is installed for this directory.
  Wanted: ${POLYVM_RESOLVE_HINT}
  Install it with: polyvm install ${POLYVM_RESOLVE_HINT}"
  fi
  if [ $rc -ne 0 ] || [ -z "$POLYVM_CMD_PATH" ]; then
    polyvm_die "no polyvm version is set for '${cmd}' in this directory.
  Set one with: polyvm local <plugin> <version>
  Or globally:  polyvm global <plugin> <version>"
  fi

  plugin="$POLYVM_CMD_PLUGIN"
  version="$POLYVM_CMD_VERSION"
  target="$POLYVM_CMD_PATH"

  if [ "$target" = "system" ]; then
    local syspath found
    syspath="$(polyvm_path_without_shims)"
    found="$(PATH="$syspath" command -v "$cmd" 2>/dev/null || true)"
    [ -n "$found" ] || polyvm_die "'$cmd' is set to the system version but is not on PATH outside polyvm"
    PATH="$syspath" exec "$found" "$@"
  fi

  polyvm_apply_exec_env "$plugin" "$version"
  exec "$target" "$@"
}

# Source the plugin's exec-env hook and put its bin dirs on PATH.
polyvm_apply_exec_env() {
  local plugin="$1" dirname="$2"
  local install_path="${POLYVM_INSTALL_DIR}/${plugin}/${dirname}"

  ASDF_INSTALL_TYPE="version"
  ASDF_INSTALL_VERSION="$dirname"
  ASDF_INSTALL_PATH="$install_path"
  POLYVM_INSTALL_PATH="$install_path"
  export ASDF_INSTALL_TYPE ASDF_INSTALL_VERSION ASDF_INSTALL_PATH POLYVM_INSTALL_PATH
  polyvm_export_hook_env "$plugin"

  local bindir newpath=""
  for bindir in $(polyvm_bin_paths "$plugin" "$dirname"); do
    [ -d "$bindir" ] || continue
    if [ -z "$newpath" ]; then newpath="$bindir"; else newpath="${newpath}:${bindir}"; fi
  done
  [ -n "$newpath" ] && PATH="${newpath}:${PATH}" && export PATH

  local hook
  hook="$(polyvm_plugin_path "$plugin")/bin/exec-env"
  if [ -f "$hook" ]; then
    # shellcheck disable=SC1090
    . "$hook"
  fi
}
